Locked virtual machines must not have expiration time
the-berta-project/berta pull request #10
Opened 2019-09-23 08:45 UTC by baby-gnu

Since OpenNebula 5.8, virtual machines can be locked to prevent
unwanted actions.

Berta must respect the lock state.

* berta.gemspec: require OpenNebula 5.8 API.

* lib/berta/service.rb (Berta::Service#running_vms): ask for extended
  information to retrive lock state.

* lib/berta/utils/filter.rb (Berta::Utils::Filter#filter_locked):
  check for any kind of lock.

* lib/berta/utils/exclude_filter.rb (Berta::Utils::ExcludeFilter#filter):
  exclude locked virtual machines.

* lib/berta/utils/include_filter.rb (Berta::Utils::IncludeFilter#filter):
  exclude locked virtual machines.

2019-09-23 09:12 UTC, dudoslav requested changes
If locked WM is option that is not specified in settings(config) file then it should not be in filter class, because it has to be excluded always. I believe that class `lib/berta/exclusions.rb` should be modified to do this. This way the change in code will be way smaller.

2019-09-23 11:26 UTC, baby-gnu commented
> If locked WM is option that is not specified in settings(config) file then it should not be in filter class, because it has to be excluded always. I believe that class `lib/berta/exclusions.rb` should be modified to do this. This way the change in code will be way smaller.

Thanks for the comment.

I should have missed something because I started by modifying `lib/berta/exclusions.rb` but it's never executed.

The class is use nowhere else than the `autoload` in `lib/berta.rb`.

Regards.

2019-09-24 08:57 UTC, baby-gnu commented
Hello @dudoslav, do you have any idea about what I'm doing wrong?

Regards.

2019-09-24 09:39 UTC, dudoslav commented
You are right, exclusions class in not used.

But anyway, you need to implement method that excludes locked vms in `lib/berta/utils/filter.rb` simmilar to how `takes_resources?` work. Basically it does the same thing, just with different predicate. This way you don't have to modify exclude and include filter, since this functionality is same across both of these classes.

2019-09-24 09:43 UTC, dudoslav commented
Basically implement private method `is_locked?` in filter class. Then use it to filter locked vms in `run` method. Like the first line in `run` method.

2019-09-25 11:02 UTC, baby-gnu commented
Thanks @dudoslav, now I understand better the architecture of filtering.

Maybe we should remove all the unused code? I'll add an issue for that.

Regards.

2019-09-25 11:14 UTC, dudoslav submitted a review, later dismissed

2019-09-25 11:37 UTC, baby-gnu commented
I'm working on testing ;-)

2019-09-25 11:45 UTC, baby-gnu commented
Now there are only problem with test infrastructure but the tests pass.

Regards.

2019-09-28 11:57 UTC, dudoslav approved these changes

2019-09-28 11:57 UTC, dudoslav commented on lib/berta/utils/filter.rb
> +        vmh.handle.has_elements?('LOCK/LOCKED') && vmh.handle['LOCK/LOCKED'] != '0'
Travis tests wont pass. `.has_elements?` is probably only supported in newer versions of ruby. We want to support ruby ~2.3, ~2.2

2019-09-28 11:59 UTC, merged